CREATE TABLE filedetails (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    DocumentName VARCHAR(255) NOT NULL,
    DocType VARCHAR(10) NOT NULL,
    DocData LONGBLOB NOT NULL,
    DocUrl VARCHAR(255) NOT NULL,
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);